### ISSUE TITLE
Update for rsync on v7r1

### ISSUE THREAD

**Issue by DucoBergsma** [IBM/ibmi-oss-issues#57] opened 2024-06-11 09:26 UTC
We installed rsync 3.1.2-1 on a v7R1 IBMi, but when using it we run into the error "Value too large to be stored in data type (127)" when syncing large files (2GB+).

Is there a newer version available for v7r1?

**Comment by markdirish** [comment] 2024-06-11 14:54
Hi @DucoBergsma ,

Unfortunately we only build and update RPMs for the oldest supported version of IBM i at any time: https://ibmi-oss-docs.readthedocs.io/en/latest/yum/README.html#what-if-i-am-on-an-ibm-i-release-no-longer-in-standard-support

That means we will never build or update our RPMs for 7.1 again. However, I am not sure the issue is necessarily related to the version you are running: On the AIX IBM community, there is a user that was running into the same issue as you: 

https://community.ibm.com/community/user/power/discussion/rsync-323-failing-with-memory-error-messages

> When I try to use rsync_32 here is the error I get:
> rsync: [generator] opendir "/net/users2/yquemba" failed: Value too large to be stored in data type (127)

Because IBM i shares many of the same "_quirks_" that IBM i does, it might be worth it to attempt the solution in the thread and see if it works for you.

**Comment by kadler** [comment] 2024-06-11 20:37
Sorry, as Mark said there are no newer versions available for 7.1 and in fact 7.1 was never _officially_ supported. I _think_ this is likely an issue with PASE, though, not with rsync itself. There was an issue found a few years ago that the "large file" bit was not being set for 64-bit PASE processes, even though it should have been. This was resolved in MF65149 for 7.2 and MF65148 for 7.3, but was never fixed for 7.1. You will need to move up to a supported IBM i release to resolve this issue.

**Closed by kadler** 2024-06-11 20:37 UTC
